spring:
  ai:
    mcp:
      server:
        name: traveling-mcp-server
        version: 1.0.0
        type: ASYNC
        sse-message-endpoint: /mcp/messages
  task:
    scheduling:
      enabled: true

server:
  port: 18083

# MCP配置已迁移到 mcp.json 文件

logging:
  level:
    com.zhouruojun.mcpserver: INFO

# 管理端点
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
