server:
  port: 8089
  tomcat:
    max-http-post-size: 10485760      # 10MB
    max-swallow-size: 10485760        # 10MB
    max-http-form-post-size: 10485760 # 10MB

logging:
  level:
    org:
      springframework:
        web:
          socket: DEBUG
          messaging: DEBUG

rpc:
  ciuser:
    name: ciuser-service-default-rpc
    rpcTimeout: 10000

